export const PALETTE_24 = [
  { name: "Butter", hex: "#FFF3B0", group: "Light" },
  { name: "Apricot", hex: "#FFD6A5", group: "Light" },
  { name: "Rose", hex: "#FFADAD", group: "Light" },
  { name: "Blossom", hex: "#FFC6FF", group: "Light" },
  { name: "Lavender", hex: "#BDB2FF", group: "Light" },
  { name: "Sky", hex: "#A0C4FF", group: "Light" },
  { name: "Mint", hex: "#CAFFBF", group: "Nature" },
  { name: "Aqua", hex: "#9BF6FF", group: "Nature" },
  { name: "Moss", hex: "#CDEAC0", group: "Nature" },
  { name: "Leaf", hex: "#B5E48C", group: "Nature" },
  { name: "Sand", hex: "#DDBEA9", group: "Nature" },
  { name: "Earth", hex: "#A98467", group: "Nature" },
  { name: "Sun", hex: "#FFB703", group: "Warm" },
  { name: "Sunset", hex: "#FB8500", group: "Warm" },
  { name: "Poppy", hex: "#E63946", group: "Warm" },
  { name: "Coral", hex: "#F28482", group: "Warm" },
  { name: "Pink", hex: "#FF99C8", group: "Warm" },
  { name: "Honey", hex: "#F6BD60", group: "Warm" },
  { name: "Ocean", hex: "#457B9D", group: "Cool" },
  { name: "Midnight", hex: "#1D3557", group: "Cool" },
  { name: "Violet", hex: "#7209B7", group: "Cool" },
  { name: "Indigo", hex: "#3A0CA3", group: "Cool" },
  { name: "Blue", hex: "#4361EE", group: "Cool" },
  { name: "Ice", hex: "#4CC9F0", group: "Cool" },
] as const;

